// Generated by CoffeeScript 1.9.0
(function() {
  var init, initialization;

  initialization = require('./initialization');

  module.exports = function(argv) {
    var parameter;
    parameter = argv[2];
    switch (parameter) {
      case 'init':
        return init();
    }
  };

  init = function() {
    return initialization();
  };

}).call(this);
