// Generated by CoffeeScript 1.9.0
(function() {
  var child_process, fs, path;

  fs = require('fs-extra');

  path = require('path');

  child_process = require('child_process');

  module.exports = function() {
    var src, target;
    src = path.join(__dirname, '../_template');
    target = process.cwd();
    return fs.copy(src, target, function(err) {
      if (err) {
        console.log('初始化失败，错误信息：');
        console.error(err);
        return;
      }
      return child_process.exec('qnpm install', function(error, stdout, stderr) {
        console.log("stdout: " + stdout);
        console.log("stderr: " + stderr);
        if (error !== null) {
          return console.log("exec error: " + error);
        } else {
          return console.log('初始化完成');
        }
      });
    });
  };

}).call(this);
